### PR TITLE
fix aggregation when nothing possible #67

### LINKED ISSUE #67: BUG: issue with missing age group in agg function
**Describe the bug**
The agg function produces this error when an age group is missing even though I have the argument `missing_dt_severity = "none"`.

`Error in colnamesInt(x, neworder, check_dups = FALSE) : 
  argument specifying columns specify non existing column(s): cols[1]='age_group_id'
In addition: Warning message:
In [.data.table(result_dt, , :=(c(col_stem), NULL)) :
  Column 'age' does not exist to remove`

It would be nice if the error was more informative because it makes it seem like the age columns are missing but they are not.

**To Reproduce**
```
dt <- data.table(age_group_id = c(7:14),
                 nid = rep(256619),
                 underlying_nid = rep(NA),
                 ihme_loc_id = rep("CAN"),
                 year_id = rep(2000),
                 sex = rep("both"),
                 births_reported = c(153, 17350, 59523, 101072, 96353, 45393, 7643, 278),
                 age_start = c(seq(10, 45, 5)),
                 age_end = c(seq(15, 50, 5)),
                 unique_identifier = rep("256619_NA_CAN_2000_both"))

age_specific_births_reported <- copy(dt)

```
```
gbd_year <- 2020

age_map <- mortdb::get_age_map(gbd_year = gbd_year, type = "all")

age_map_10_54 <- age_map[age_group_id == 169, c("age_group_years_start", "age_group_years_end")]
colnames(age_map_10_54) <- c("age_start", "age_end")

value_cols <- "births_reported"
id_cols <- names(age_specific_births_reported)[!names(age_specific_births_reported) %in% value_cols]

age_specific_agg_age_10_54 <- data.table()

for (i in unique(age_specific_births_reported$unique_identifier)) {
  
  temp <- age_specific_births_reported[unique_identifier == i, ]
  
  temp_agg <- hierarchyUtils::agg(
    dt = temp,
    id_cols = id_cols,
    value_cols = value_cols,
    col_stem = "age",
    col_type = "interval",
    mapping = age_map_10_54,
    missing_dt_severity = "none",
    present_agg_severity = "skip",
    overlapping_dt_severity = "stop"
  )
  
  age_specific_agg_age_10_54 <- rbind(age_specific_agg_age_10_54, temp_agg)
  
  temp_agg <- NULL
  
}

```

### PR DESCRIPTION
**Pull request by chacalle**
## Describe changes

Fixes #67, flagged by @hcomfo95. Where the requested aggregate was age 10-55 but data only had 15-55. Called with `missing_dt_severity = "none"`. Since the requested aggregate is not possible, the function should have returned an empty data.table but was instead erroring out with an obscure error.

```
none: don't throw error or warning, continue with aggregation/scaling for requested aggregations/scalings where expected input data in dt is available.

skip: skip this check and continue with aggregation/scaling.
```

If instead @hcomfo95 expected to still make the aggregate even though it was missing input age group values I fixed `missing_dt_severity = "skip"` so that it still goes ahead and makes the aggregate.

@erinamay I were talking about a similar situation this week where there are implied zeroes or unknown values in the input dataset. Like in this example 10-15 is unknown or implied zero. We likely need helper functions to fill in implied zeroes and then a better way to handle unknown id columns (like age) or value columns. Related to #49 and #65

### Packages Repositories

* [X] Have you read the [contributing guidelines](https://github.com/ihmeuw-demographics/packageTemplate/wiki#guide-to-r-package-development) for `ihmeuw-demographics` R packages?
* [X] Have you successfully run `devtools::check()` locally?
* [X] Have you updated or added function (and vignette if applicable) documentation? Did you update the 'man' and 'NAMESPACE' files with `devtools::document()`?
* [X] Have you added in tests for the changes included in the PR?
* [X] Do the changes follow the `ihmeuw-demographics` [code style](https://github.com/ihmeuw-demographics/packageTemplate/wiki/Code-style-guide)?
* [ ] Do the changes need to be immediately included in a new build of [`docker-base`](https://github.com/ihmeuw-demographics/docker-base) or [`docker-internal`](https://github.com/ihmeuw-demographics/docker-internal)? If so follow directions in those repositories to rebuild and redeploy the images.
* [ ] Do the changes require updates to other repositories which use this package? If yes, make the necessary updates in those repos, and consider integration tests for those repositories.
* [ ] If this is a private package did you use Jenkins to rebuild the internal pkgdown site?

### CODE REVIEW

**Review by hcomfo95 — APPROVED** [review]
Should this function also output the missing age group(s)? Then we can confirm it is the youngest or oldest age groups that are not present in the data. There could be bad implications if an age group in the middle was missing due to an extraction error or something but wasn't caught because of the skip.

**Comment by erinamay** [comment]
I agree with Haley it could still be confusing to get an empty table returned. If there was some kind of message saying missing x ages that would be super helpful!

**Review by erinamay — APPROVED** [review]

**Comment by chacalle** [comment]
If `missing_dt_severity` is set to stop, warning, or message it does print out the missing age groups. Is this just a case of generally not recommending `none` since it does the same thing as warning or message, but hides potentially important information?

```
stop: throw error (this is the default).

warning or message: throw warning/message and continue with aggregation/scaling for requested aggregations/scalings where expected input data in dt is available.

none: don't throw error or warning, continue with aggregation/scaling for requested aggregations/scalings where expected input data in dt is available.

skip: skip this check and continue with aggregation/scaling.
```

**Comment by chacalle** [comment]
We could also consider saving problematic rows (overlapping intervals, missing intervals) as different attributes of the returned object so that someone could inspect more. 

Also could encourage more checks using helper functions prior to calling `agg`. Especially if ignoring checks within `agg`.

**Pull request merged**
